### ISSUE TITLE
如何编译，需要什么环境和软件支持？

### ISSUE THREAD

**Issue by lzwling** [bg6cq/ethudp#1]
RT

**Comment by bg6cq** [comment]
我在centos下编译，需要gcc, openssl-devel, lz4-devel, 别的不需要

**Comment by lzwling** [comment]
CentOS 7  make
[root@localhost ethudp]# make
gcc -g -Wall -o EthUDP EthUDP.c -lpthread -lssl -llz4
/bin/ld: /tmp/ccBwUElx.o: undefined reference to symbol 'EVP_EncryptUpdate@@libc                                                       rypto.so.10'
/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [EthUDP] Error 1
[root@localhost ethudp]# 

修改Makefile，gcc 加 -lcrypto 后可以便宜成功

另外装了一台Debian8 
make

root@localhost:/usr/local/src/ethudp# make
gcc -g -Wall -o EthUDP EthUDP.c -lpthread -lssl -llz4
EthUDP.c: In function ‘do_encrypt’:
EthUDP.c:456:3: warning: implicit declaration of function ‘LZ4_compress_fast’ [-Wimplicit-function-declaration]
   nlen = LZ4_compress_fast((char *)buf, (char *)lzbuf, len, len + LZ4_SPACE, lz4);
   ^
EthUDP.c: In function ‘process_raw_to_udp’:
EthUDP.c:1079:5: error: expected ‘;’ before ‘tag’
     tag->vlan_tci = htons(aux->tp_vlan_tci);
     ^
EthUDP.c: In function ‘main’:
EthUDP.c:1450:4: warning: ‘memset’ used with constant zero length parameter; this could be due to transposed parameters [-Wmemset-transposed-args]
    memset(enc_key, MAXLEN, 0);
    ^
Makefile:2: recipe for target 'EthUDP' failed
make: *** [EthUDP] Error 1
root@localhost:/usr/local/src/ethudp#

改了  1079行末尾少 ； 分号，同样加-lcrypto

再次make

gcc -g -Wall -o EthUDP EthUDP.c -lpthread -lssl -llz4 -lcrypto
EthUDP.c: In function ‘do_encrypt’:
EthUDP.c:456:3: warning: implicit declaration of function ‘LZ4_compress_fast’ [-Wimplicit-function-declaration]
   nlen = LZ4_compress_fast((char *)buf, (char *)lzbuf, len, len + LZ4_SPACE, lz4);
   ^
EthUDP.c: In function ‘main’:
EthUDP.c:1450:4: warning: ‘memset’ used with constant zero length parameter; this could be due to transposed parameters [-Wmemset-transposed-args]
    memset(enc_key, MAXLEN, 0);
    ^
/tmp/ccEkbw9Q.o：在函数‘do_encrypt’中：
/usr/local/src/ethudp/EthUDP.c:456：对‘LZ4_compress_fast’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'EthUDP' failed
make: *** [EthUDP] Error 1

#
暂时还没有解决

**Comment by bg6cq** [comment]
谢谢找出前面2个bug。

Debian 默认的liblz4-dev比较老缺少一些函数，
我参考 https://github.com/facebook/mcrouter/issues/149
重新编译安装后解决了

**Comment by lzwling** [comment]
好了，OK了

**Comment by Yuanyiis** [comment]
@bg6cq   请问和n2n相比 有没有速度和延迟的优势呢？
想替代n2n

**Comment by bg6cq** [comment]
抱歉，不了解n2n
